---
- name: Reset all access ports on multiple devices
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Search config for access ports
      ios_command:
        commands: show run | inc interface | switchport mode
      register: sh_interfaces_output
  
    - name: Reset access ports  group 1 (1/0/1 - 48)
      ios_config:
        lines:
        - shutdown
        - no shutdown
        parents: '{{ item }}'
      with_items:
      - Interface GigabitEthernet1/0/1
      - Interface GigabitEthernet1/0/2
      - Interface GigabitEthernet1/0/3
      - Interface GigabitEthernet1/0/4
      - Interface GigabitEthernet1/0/5
      - Interface GigabitEthernet1/0/6
      - Interface GigabitEthernet1/0/7
      - Interface GigabitEthernet1/0/8
      - Interface GigabitEthernet1/0/9
      - Interface GigabitEthernet1/0/10
      - Interface GigabitEthernet1/0/11
      - Interface GigabitEthernet1/0/12
      - Interface GigabitEthernet1/0/13
      - Interface GigabitEthernet1/0/14
      - Interface GigabitEthernet1/0/15
      - Interface GigabitEthernet1/0/16
      - Interface GigabitEthernet1/0/17
      - Interface GigabitEthernet1/0/18
      - Interface GigabitEthernet1/0/19
      - Interface GigabitEthernet1/0/20
      - Interface GigabitEthernet1/0/21
      - Interface GigabitEthernet1/0/22
      - Interface GigabitEthernet1/0/23
      - Interface GigabitEthernet1/0/24
      - Interface GigabitEthernet1/0/25
      - Interface GigabitEthernet1/0/26
      - Interface GigabitEthernet1/0/27
      - Interface GigabitEthernet1/0/28
      - Interface GigabitEthernet1/0/29
      - Interface GigabitEthernet1/0/30
      - Interface GigabitEthernet1/0/31
      - Interface GigabitEthernet1/0/32
      - Interface GigabitEthernet1/0/33
      - Interface GigabitEthernet1/0/34
      - Interface GigabitEthernet1/0/35
      - Interface GigabitEthernet1/0/36
      - Interface GigabitEthernet1/0/37
      - Interface GigabitEthernet1/0/38
      - Interface GigabitEthernet1/0/39
      - Interface GigabitEthernet1/0/40
      - Interface GigabitEthernet1/0/42
      - Interface GigabitEthernet1/0/43
      - Interface GigabitEthernet1/0/44
      - Interface GigabitEthernet1/0/45
      - Interface GigabitEthernet1/0/46
      - Interface GigabitEthernet1/0/47
      - Interface GigabitEthernet1/0/48 
      #when: sh_interfaces_output is search("switchport mode access")
