---
- name: Reset all access ports on multiple devices
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Search config for access ports
      ios_command:
        commands: 
        - show  run interface  e0/1
        - show  run interface  e0/2
        - show  run interface  e0/3
      register: 
      - e0/1
      - e0/2
      - e0/3
      
    - name: Reset access ports
      ios_config:
        lines:
        - shutdown
        - description  TEST1
        parents: '{{ item }}'
      with_items:
      - interface Ethernet0/1
      - interface Ethernet0/2
      - interface Ethernet0/3
      when:
      - e0/1 is search("switchport mode access")
      - e0/2 is search("switchport mode access")
      - e0/3 is search("switchport mode access")
