---
- name: Reset all access ports on multiple devices
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Search config for access ports
      ios_command:
        commands: 
        - show interface e0/1 switchport | inc Administrative Mode
        - show interface e0/2 switchport | inc Administrative Mode
        - show interface e0/3 switchport | inc Administrative Mode
      register: sh_interfaces_output
  
    - name: Reset access ports  group 1 (Ethernet0/1 - 3)
      ios_config:
        lines:
        - no shutdown
        - description Ansible is a Lady
        parents: interface range Ethernet0/1 - 3
      when: sh_interfaces_output is search(" static access ")
    
    #- name: Pause for 1 minute to allow ports to finish
      #ansible.builtin.pause:
        #minutes: 1
      
    #- name: Reset access ports  group 2 (1/0/24 - 48)
      #ios_config:
        #lines:
        #- shut
        #- no shut 
        #parents: interface range GigabitEthernet 1/0/24 - 48
      #when: sh_interfaces_output is search("switchport mode access")
