---
- hosts: all
  gather_facts: false
  connection: network_cli 
  tasks:
    - name: Create new VLAN 
      cisco.ios.ios_vlans:
        config:
        - name: {{vlan_name}}
          vlan_id: {{vlan_id}}
          state: active
      
    - name: save running to startup when modified
      ios_config:
        save_when: modified
