---
- hosts: all
  gather_facts: false
  connection: local 
  
  tasks:
    - name: Override device configuration of all VLANs with provided configuration
      cisco.ios.ios_vlans:
        config:
    - name: Vlan {{vlan_name}}
      vlan_id: "{{vlan_id}}"
      state: active
      
    - name: save running to startup when modified
      ios_config:
        save_when: modified
