---
- hosts: all
  gather_facts: false
  connection: network_cli
  #### ansible_network_os: ios <--add this statement to the AWX TEMPLATE in the Variables section
  tasks:
    - name: Create new VLAN 
      cisco.ios.ios_vlans:
        config:
        - name: CHECK_3
          vlan_id: 80
          #state: active
      
    - name: save running to startup when modified
      ios_config:
        save_when: modified
