---
- hosts: all
  gather_facts: false
  connection: local 
  tasks:
    - name: Create new VLAN 
      cisco.ios.ios_vlans:
        aggregate:
        - {vlan_id: "{{ vlan_id }}" , name: "{{ vlan_name }}" , interfaces: "{{ interface }}" }
      
        - name: save running to startup when modified
          ios_config:
            save_when: modified
