---
- name: backup commands
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: show run 
      ios_command:
        commands:
          - show run
      register: config

    - name: save output to /home/ansible/backups 
      copy: 
         content: "{{ config.stdout[0] }}"
         dest: "/home/ansible/backups/show_run_{{ inventory_hostname }}.txt"
...
