---
- name: "Play1"
  hosts: localhost
  
  tasks:
    - name: "Task 1 of Play1: Collect facts about local host"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"
          
    - name: "Task2 of Play1:: Recording Variable" 
      set_fact:
        TD: "{{ ansible_date_time.date }}"
    
    - name: "Task 3 of lay 1: Create new directories"
      file:
        path: "/home/ansible/backups/{{ TD }}"
        state: directory
      run_once: true  
    
   
- name: "Play2: Backup up Configurations"
  hosts: all
  connection: network_cli
      
  tasks:
    - name: show run 
      ios_command:
        commands:
          - show run
      register: config
              

    - name: save output to /home/ansible/backups
      copy: 
        content: "{{ config.stdout[0] }}"
        dest: "/home/ansible/backups/{{TD}}/{{inventory_group}}_{{ inventory_hostname }}.txt"
