---
- name: backup commands
  hosts: all
  gather_facts: False
  connection: local
  tasks:
    - name: show run 
      ios_command:
        commands:
          - show run
      register: config

    - name: save output to /home/ansible/backups 
      copy: 
         content: "{{ config.stdout[0] }}"
         dest: "/home/ansible/backups/{{inventory_group}}_{{ inventory_hostname }}.txt"
         
    - name: copy from containter to /home/ansible/backups  
      copy: 
         src:  "awx_task:/home/ansible/backups/    /home/ansible/backups/"
         dest: "/home/ansible/backups/{{inventory_group}}_{{run_date}}_{{ inventory_hostname }}.txt"
...   #become: true 
