---
- name: create 4 loopback intefaces
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: Loopback0
          ipv4:
          - address: "{{loopback0_ip}}" 
        
        - name: Loopback1
          ipv4:
          - address: "{{loopback1_ip}}" 
        
        - name: Loopback2
          ipv4:
          - address: "{{loopback2_ip}}" 
        - name: Loopback3
          ipv4:
          - address: "{{loopback3_ip}}" 
        state: merged
