---
- name: create trunk ports
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Delete interfaces 
      cisco.ios.ios_interfaces:
        config:
        - name: "{{trunk_port1}}"
        state: deleted
    
    - name: Delete interfaces
      cisco.ios.ios_interfaces:
        config:
        - name: "{{trunk_port2}}"
        state: deleted
    
    - name: Delete interfaces
      cisco.ios.ios_interfaces:
        config:
        - name: "{{trunk_port3}}"
        state: deleted
    
    - name: Delete interfaces
      cisco.ios.ios_interfaces:
        config:
        - name: "{{trunk_port4}}"
        state: delete 
  
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port1}}"
          mode: trunk
          trunk:
            encapsulation: dot1q
        
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port2}}"
          mode: trunk
          trunk:
            encapsulation: dot1q    
    
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port3}}"
          mode: trunk
          trunk:
            encapsulation: dot1q
    
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port4}}"
          mode: trunk
          trunk:
            encapsulation: dot1q
