---
- name: create trunk ports
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port1}}"
          mode: trunk
          trunk:
            #allowed_vlans: All
            #native_vlan: 20
            #pruning_vlans: 10,20
            encapsulation: dot1q
    #state: merged
    
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port2}}"
          mode: trunk
          trunk:
            #allowed_vlans: All
            #native_vlan: 20
            #pruning_vlans: 10,20
            encapsulation: dot1q
    state: merged
    
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port3}}"
          mode: trunk
          trunk:
            #allowed_vlans: All
            #native_vlan: 20
            #pruning_vlans: 10,20
            encapsulation: dot1q
    #state: merged
    
    - name: Enable trunking on port
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{trunk_port4}}"
          mode: trunk
          trunk:
            #allowed_vlans: All
            #native_vlan: 20
            #pruning_vlans: 10,20
            encapsulation: dot1q
    #state: merged
    
