---
- name: create 4 loopback intefaces
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: loopback0
          ipv4:
          - address: "{{loopback0_ip}}" /24
        
        - name: loopback1
          ipv4:
          - address: "{{loopback1_ip}}" /24
        
        - name: loopback2
          ipv4:
          - address: "{{loopback2_ip}}" /24
        - name: loopback3
          ipv4:
          - address: "{{loopback3_ip}}" /24
        state: merged
