---
- name: file permission update
  hosts: all
  vars:
    myfile: "/media/VOL2/VIDS4/"
  become: false
  tasks:
    - name: check permission
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: directory
        recurse: yes
        owner: "mark"
        group: "mark"
        mode: '0777'
    - name: check permission folder 3
      ansible.builtin.file:
        path: "/media/VOL2/VIDS3/"
        state: directory
        recurse: yes
        owner: "mark"
        group: "mark"
        mode: '0777'
    - name: check permission folder 2
      ansible.builtin.file:
        path: "/media/VOL2/VIDS2/"
        state: directory
        recurse: yes
        owner: "mark"
        group: "mark"
        mode: '0777'
    - name: check permission folder 1
      ansible.builtin.file:
        path: "/media/VOL2/VIDS1/"
        state: directory
        recurse: yes
