---
- name: Test IOS Facts
  hosts: all
  connection: local
  tasks:
    - name: Gather all legacy facts
      ios_facts:
        gather_subset: all
      register: all_subset
     
    - name: Print Subset All
      debug:
        var: all_subset
        
    
        
