---
- name: Disable ISE from a  range of ports  
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Remove ISE from  1st group of ports 
      ios_config:
        lines:
        - no description
        - no authentication event server dead action reinitialize vlan {{vlan_id}}    
        - no authentication event server dead action authorize voice 
        - no authentication event server alive action reinitialize        
        parents: interface range {{port_range_1}}
        
    - name: Pause for 1 minute to allow ports to finish
      ansible.builtin.pause:
        minutes: 1  
