---
- name: Disable ISE from a  range of ports  
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Remove ISE from  1st group of ports 
      ios_config:
        lines:
        # - no authentication event server dead action reinitialize vlan 
        - no authentication event server dead action authorize voice 
        - no authentication event server alive action reinitialize     
        - no authentication host-mode multi-auth
        - no authentication order dot1x mab
        - no authentication priority dot1x mab        
        - no authentication port-control auto
        - no authentication periodic
        - no authentication timer reauthenticate server
        - no authentication timer inactivity server
        - no authentication violation restrict
        - no mab
        - no dot1x pae authenticator
        - no dot1x timeout tx-period
        - no dot1x max-reauth-req 1     
        parents: interface range {{port_range_1}}
        
    - name: Pause for 1 minute to allow ports to finish
      ansible.builtin.pause:
        minutes: 1  
