---
- name: Disable ISE from a  range of ports  
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Disable ISE on group of ports 
      ios_config:
        lines:
        - no authentication control-direction in 
        - no authentication event fail action next-method
        #- no authentication event server dead action reinitialize vlan {{vlan_id}}
        - no authentication event server dead action authorize voice 
        - no authentication event server alive action reinitialize        
        - no authentication host-mode multi-auth
        - no authentication order dot1x mab
        - no authentication priority dot1x mab        
        - no authentication port-control auto
        - no authentication periodic
        - no authentication timer reauthenticate server
        - no authentication timer inactivity server
        - no authentication violation restrict
        - no mab
        - no dot1x pae authenticator
        - no dot1x timeout tx-period
        - no dot1x max-reauth-req 1
        parents: interface range {{port_range_1}}
        
    - name: Pause for 1 minute to allow ports to finish receiving config update
      ansible.builtin.pause:
        minutes: 1    
    
    - name: Pause for 1 minute to allow ports to finish
      ansible.builtin.pause:
        minutes: {{pause_time}}
        
    - name: Enable  ISE on group of ports 
      ios_config:
        lines:
        - authentication control-direction in 
        - authentication event fail action next-method
        # - authentication event server dead action reinitialize vlan {{vlan_id}}
        - authentication event server dead action authorize voice 
        - authentication event server alive action reinitialize        
        - authentication host-mode multi-auth
        - authentication order dot1x mab
        - authentication priority dot1x mab        
        - authentication port-control auto
        - authentication periodic
        - authentication timer reauthenticate server
        - authentication timer inactivity server
        - authentication violation restrict
        - mab
        - dot1x pae authenticator
        - dot1x timeout tx-period
        - dot1x max-reauth-req 1
        parents: interface range {{port_range_1}}
        
    - name: Pause for 1 minute to allow ports to finish receiving config update
      ansible.builtin.pause:
        minutes: 1       
        
   
