---
- name: Disable ISE from a  range of ports  
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Remove ISE from  1st group of ports 
      ios_config:
        lines:
        - no authentication control-direction in 
        - no authentication event fail action next-method
      parents: interface range "{{port_range_1}}"
        
    - name: Pause for 1 minute to allow ports to finish
      ansible.builtin.pause:
        minutes: 1  
