---

- name: "Loop test"
  hosts: all
  gather_facts: true
  connection: network_cli

  tasks:
    - name: "Loop through Serial numbers"
      debug:
        msg: "{{ [ansible_net_hostname] }} has a serial number {{ item }} "
      loop: "{{ [ansible_net_serialnum] }}"

