---
- name: Ping test to a group of external hosts 
  hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli  
  tasks:
    - name: Test reachability to external hosts
      cisco.ios.ios_ping:
        dest: 8.8.8.8
