---
- name: Update range of ports  
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: update range of ports 
      ios_config:
        lines:
        - description port range test
        - cdp enable
        parents: interface range gigabit 1 - 3 
        
