---
- name: "backup files to curret directory in backup folder"
  hosts: all
  gather_facts: False
  connection: network_cli 
  tasks:
    - name: Backup current switch config (ios)
      cisco.ios.ios_config:
        backup: yes  
      register: backup_ios_location
      when: ansible_network_os == 'cisco.ios.ios'
