---
- name: Remove enable secret 
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: remove enable secret from config 
      ios_config:
          lines: no enable secret     
         
    - name: save running to startup when modified
      ios_config:
        save_when: modified
