---
- name: Switch Report Brief
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Show ip int brief
      ios_command:
        commands: show ip int brief
      vars:
        ansible_command_timeout: 60
      register: if_data

    - name: Interfaces output
      debug:
        var: if_data['stdout_lines'][0]
   
    - name: Show interface summary
      ios_command:
        commands: 
        - show interface summary 
        - show interface counters protocol status
      vars:
        ansible_command_timeout: 60
      register: if_data2
     
    - name: Interfaces Output2
      debug:
        var: if_data2['stdout_lines'][0] 
      
      
    - name: Show inventory 
      ios_command:
        commands: 
        - show inventory 
        - show log  
      vars:
        ansible_command_timeout: 60
      register: if_data3

    - name: Interfaces Output3
      debug:
        var: if_data3['stdout_lines'][0] 
        
    - name: Show log 
      ios_command:
        commands: 
        - show log | inc "{{date}}"
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: Interfaces Output3
      debug:
        var: if_data4['stdout_lines'][0] 


   
