---
- name: show int status 
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Show int status 
      ios_command:
        commands: 
        - show interface summary 
       #- show int status | inc connected
      vars:
        ansible_command_timeout: 60
      register: if_data

    - name: Output1
      debug:
        var: if_data['stdout_lines'][0]
   
    - name: show interface stats
      ios_command:
        commands: 
        - show interface stats
        #- show int status | count  connected
      vars:
        ansible_command_timeout: 60
      register: if_data2
     
    - name: Output2
      debug:
        var: if_data2['stdout_lines'][0] 
      
      
    - name: Show arp  
      ios_command:
        commands: 
        - show arp 
        # - show mac address-table  | inc DYNAMIC 
        # - show mac address-table  | count DYNAMIC  
      vars:
        ansible_command_timeout: 60
      register: if_data3

    - name: Output3
      debug:
        var: if_data3['stdout_lines'][0] 
      
       
    - name: Show ip int brie 
      ios_command:
        commands: 
        - show ip int brie | exc unassigned
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: Output 5
      debug:
        var: if_data4['stdout_lines'][0] 
   
    - name: Show inventory 
      ios_command:
        commands: 
        - show inventory
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: Output 6
      debug:
        var: if_data4['stdout_lines'][0] 
        
    - name: Show log 
      ios_command:
        commands: 
        - show log | inc {{Mo}}  {{Date}}
      vars:
        ansible_command_timeout: 60
      register: if_data4

    - name: Output 7
      debug:
        var: if_data4['stdout_lines'][0] 
    
    #- name: ping  
    #  ios_command:
    #    commands: 
    #    - ping 8.8.8.8
    #    - ping 8.8.4.4
    #  vars:
    #    ansible_command_timeout: 60
    #  register: if_data4
      
    #- name: Output 8
    #  debug:
    #    var: if_data4['stdout_lines'][0] 
    
     
        
    - name: Sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: netconexxions@gmail.com
        password: <password>
        to: John Smith <mark.dawkins@gmail.com>
        subject: Ansible-report
        body: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: localhost    
    
    #- name: Add email notification
    #  notification_template:
    #    name: TEST_Notification
    #    notification_type: email
    #    notification_configuration:
    #      username: netconexxions
    #      password: <password>
    #      sender: netconexxions@gmail.com
    #      recipients:
    #        - mark.dawkins@gmail.com
    #      host: smtp.gmail.com
    #      port: 25
    #      use_tls: no
    #      use_ssl: no
    #    state: present
    #    controller_config_file: "~/tower_cli.cfg
    

