- name: "Test PLAYBOOK"
  hosts: all
  connection: local 
  tasks:
    - name: "Collect facts about local host"
      ansible.builtin.setup:
        filter:
      register: output
    - name: "Print stuff"
      debug:
        msg: "{{ output.ansible_facts.ansible_date_time.date }}"
