---
- name: Configure Telnet Devices
  hosts: all
  gather_facts: false

  tasks:
    - name: Run show commands
      telnet:
        user: "{{telnet_user}}"
        password: "{{telnet_pass}}"
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command: 
        #- terminal length 0 
        - show ip int brief
        vars:
          ansible_command_timeout: 60
        register: if_data

    - name: Output1
      debug:
        var: if_data['stdout_lines'][0]

