---
- name: Configure Telnet Devices
  hosts: all
  gather_facts: false

  tasks:
    - name: Send configuration commands to IOS
      telnet:
        user: "{{telnet_user}}"
        password: "{{telnet_pass}}"
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command:
          - configure terminal
          - username sparky privilege 15 password go
          

    
