---
- name: Configure Telnet Devices
  hosts: all
  gather_facts: false

  tasks:
    - name: Send configuration commands to IOS
      telnet:
        user: ansible
        password: go
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command:
          - terminal length 0
          - configure terminal
          - hostname zzzzz

    - name: Run show commands
      telnet:
        user: ansible
        password: go
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command:
          - terminal length 0
          - show version
