---
- name: Configure Telnet Devices
  hosts: all
  gather_facts: false

  tasks:
    - name: Send configuration commands to IOS
      telnet:
        user: "{{telnet_user}}"
        password: "{{telnet_pass}}"
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command:
          - terminal length 0
          - configure terminal
          - hostname csr02

    - name: Run show commands
      telnet:
        user: "{{telnet_user}}"
        password: "{{telnet_pass}}"
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command: show ip int brief
      vars:
        ansible_command_timeout: 10
      register: if_data
          
    - name: Interfaces output
      debug:
        var: if_data['stdout_lines'][0]
