---
- name: Configure Telnet Devices
  hosts: all
  gather_facts: false

  tasks:
    - name: Run show commands
      telnet:
        user: "{{telnet_user}}"
        password: "{{telnet_pass}}"
        login_prompt: "Username: "
        prompts:
          - "[>#]"
        command: show ip int brief
      vars:
        register: if_data
          
    - name: Output
      debug:
        var: if_data['stdout_lines'][0]
