---
- name: "Play1"
  hosts: all
  connection: network_cli
  tasks: 
    - name: "Play1_1: Gather all Legacy facts"
      cisco.ios.ios_facts:
        gather_subset: 
        - config 
      register: result
      debug:
        msg: "{{ result }}"
