---
- hosts: ise_servers
  gather_facts: false
  tasks:
        - name: Create or update a network device
      cisco.ise.network_device:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: "{{device_name }}"
        NetworkDeviceIPList:
          - ipaddress: "{{ ipaddress }}"
            mask: 32
      register: result

  
